### PR TITLE
投稿：《神经网络算法的优势与应用》

### PR DESCRIPTION
**Pull request by workchenhao**
…cations.md

### CODE REVIEW

**Comment by Lchiffon** [comment]
感谢投稿, 这是一篇译文, 请主编分派任务
@PuddingNnn

**Comment by PuddingNnn** [comment]
@workchenhao 感谢您的投稿，能否先跟原作者确认授权，这样统计之都审稿之后可以发布出来，谢谢！

**Comment by workchenhao** [comment]
已与原作者申请授权，以下是原作者回复以及要求：

Hi,

Sure, you can do that, but would really require you to give me credit saying that the article is a translated one from a kdnuggets post from me

The other request is that - at the end of my article in kdnuggets, I put my bio, so if you can also publish that. Specifically, if you can publish the below at the end:

"To learn ANNs in more detail, register for the 8 week Data science course on www.deeplearningtrack.com – next batch starting soon."

Please do send me the link of the published article, when it gets published

Thanks
Jahnavi

**Comment by Gwill** [comment]
- 文件命名的格式还是不对，仔细看官网说明
- PR 的标题和描述都要写清楚

**Comment by Lchiffon** [comment]
里面作者要求加的内容有点像变向的打广告, 我个人不太喜欢这样的方式.

**Comment by PuddingNnn** [comment]
@workchenhao 您好 cos不能接受广告形式的文本，非常抱歉，我们不能接受这个稿件。不过，我们非常欢迎您以原创形式投稿，如果是翻译稿件，请确保没有广告形式，谢谢您，期待您的大作

**Comment by workchenhao** [comment]
好的，了解。

**Pull request closed without merging**
